# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfe707fafdee3e5e13d923d05993df9d0515fee78bac442e31aa26dc7e71b70ad1597ca222eedd16d971c9a09a6da1640d038792768292c09fa09000aeadad65

test:
  secret_key_base: cc3ee5dc7ba4cc39d23219d5680012cec4e9e4229e90cfd8115ede501d95a2930ebd455048538354beb6b5051381cd0d0187f75b408f882551bba417b2c85c85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
